// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaoSJJZJxQ5ogWKGZuBTNPy1JLpEoo4Zs',
    appId: '1:887624952960:web:89312c5f59975f3dceca65',
    messagingSenderId: '887624952960',
    projectId: 'read-aloud-ml',
    authDomain: 'read-aloud-ml.firebaseapp.com',
    storageBucket: 'read-aloud-ml.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3L6ZGg5eaytUQia7eKX1h0LyhsPGPd0',
    appId: '1:887624952960:android:b4a2e85e0d58bf76ceca65',
    messagingSenderId: '887624952960',
    projectId: 'read-aloud-ml',
    storageBucket: 'read-aloud-ml.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmPopl4Je5NQSg67XTJbLvs74ZKhuNeco',
    appId: '1:887624952960:ios:bd3e2612afcbb5fdceca65',
    messagingSenderId: '887624952960',
    projectId: 'read-aloud-ml',
    storageBucket: 'read-aloud-ml.appspot.com',
    iosBundleId: 'com.example.readAloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmPopl4Je5NQSg67XTJbLvs74ZKhuNeco',
    appId: '1:887624952960:ios:bd3e2612afcbb5fdceca65',
    messagingSenderId: '887624952960',
    projectId: 'read-aloud-ml',
    storageBucket: 'read-aloud-ml.appspot.com',
    iosBundleId: 'com.example.readAloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaoSJJZJxQ5ogWKGZuBTNPy1JLpEoo4Zs',
    appId: '1:887624952960:web:10cb7825eef70629ceca65',
    messagingSenderId: '887624952960',
    projectId: 'read-aloud-ml',
    authDomain: 'read-aloud-ml.firebaseapp.com',
    storageBucket: 'read-aloud-ml.appspot.com',
  );
}
